// HERMES ADMIN BOT
const https = require("https");
const fs = require("fs");
const { execSync } = require("child_process");
const TOKEN = process.env.HERMES_ADMIN_TLM_BOT;
const ADMIN_ID = parseInt(process.env.TELEGRAM_ADMIN_CHAT_ID || "309921562");
const DEEPSEEK_KEY = process.env.DEEPSEEK_API_KEY || "";
let offset = 0;
function api(method, body) { return new Promise((resolve) => { const data = JSON.stringify(body); const req = https.request({ hostname: "api.telegram.org", path: '/bot'+TOKEN+'/'+method, method: "POST", headers: { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(data) } }, res => { let d = ""; res.on("data", c => d += c); res.on("end", () => { try { resolve(JSON.parse(d)); } catch { resolve({}); } }); }); req.on("error", () => resolve({})); req.write(data); req.end(); }); }
function send(text) { return api("sendMessage", { chat_id: ADMIN_ID, text, parse_mode: "HTML" }); }
function readPicks() { try { const paths = ["/repo/src/App.js", "./src/App.js"]; let appJs = ""; for (const p of paths) { try { appJs = fs.readFileSync(p, "utf8"); if (appJs) break; } catch {} } if (!appJs) return []; const match = appJs.match(/var picks = \[([\s\S]*?)\];/); if (!match) return []; return match[1].split("\n").filter(l => l.trim().startsWith("[")).map(line => { const parts = line.match(/\["([^"]+)","([^"]+)","([^"]+)","([^"]+)","([^"]+)","([^"]+)"/); return parts ? { date: parts[1], match: parts[2], bet: parts[3], odds: parts[4], score: parts[5], result: parts[6] } : null; }).filter(Boolean); } catch { return []; } }
async function handleCommand(text) { const cmd = text.trim().toLowerCase(); if (cmd === "/start") return "Hermes Admin Bot. Tape /help"; if (cmd === "/stats" || cmd === "stats") { const picks = readPicks(); const w = picks.filter(p => p.result === "GAGNE").length; const l = picks.filter(p => p.result === "PERDU").length; const pend = picks.filter(p => p.result === "EN ATTENTE"); let msg = "STATS\n" + w + "G " + l + "P " + (w+l>0?Math.round(w/(w+l)*100):0) + "%\n"; if (pend.length) { msg += "\nEn attente:\n"; pend.forEach(p => { msg += p.date + " " + p.match + " @" + p.odds + "\n"; }); } return msg; } if (cmd === "/picks") { const picks = readPicks().slice(0,10); return picks.map(p => (p.result==="GAGNE"?"V":p.result==="PERDU"?"X":"?") + " " + p.date + " " + p.match + " @" + p.odds).join("\n"); } if (cmd === "/help" || cmd === "/aide") return "Commandes: /stats /picks /help\nNaturel: Russia gagne 3-0"; return "Tape /help"; }
async function poll() { console.log("Hermes Admin Bot started"); if (!TOKEN) { console.error("Token missing"); return; } while (true) { try { const res = await api("getUpdates", { offset, timeout: 30, allowed_updates: ["message"] }); if (res.ok && res.result && res.result.length) { for (const u of res.result) { offset = u.update_id + 1; if (u.message && u.message.chat && u.message.chat.id !== ADMIN_ID) { await api("sendMessage",{chat_id:u.message.chat.id,text:"Access denied"}); continue; } if (u.message && u.message.text) await send(await handleCommand(u.message.text)); } } } catch(e) { console.error("Poll:",e.message); await new Promise(r=>setTimeout(r,5000)); } } }
poll();