'use strict';
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const active=["en/ai-football-predictions/index.html","en/football-predictions-today/index.html","en/index.html","es/index.html","es/pronosticos-futbol-hoy/index.html","es/pronosticos-futbol-ia/index.html","fr/index.html","fr/pronostics-foot-aujourdhui/index.html","fr/pronostics-foot-ia/index.html","pt-br/index.html","pt-br/palpites-futebol-hoje/index.html","pt-br/palpites-futebol-ia/index.html","ru/index.html","ru/prognozy-futbol-ii/index.html","ru/prognozy-futbol-segodnya/index.html","zh-cn/ai-zuqiu-yuce/index.html","zh-cn/index.html","zh-cn/jinri-zuqiu-yuce/index.html"];
const oldPages=["en/over-2-5-goals-predictions/index.html","en/under-2-5-goals-predictions/index.html","es/pronosticos-mas-de-2-5-goles/index.html","es/pronosticos-menos-de-2-5-goles/index.html","fr/pronostics-over-2-5/index.html","fr/pronostics-under-2-5/index.html","pt-br/palpites-mais-de-2-5-gols/index.html","pt-br/palpites-menos-de-2-5-gols/index.html","ru/total-bolshe-2-5/index.html","ru/total-menshe-2-5/index.html","zh-cn/da-2-5-qiu-yuce/index.html","zh-cn/xiao-2-5-qiu-yuce/index.html"];
const oldGuides=["btts-ou-over-25","comprendre-over-under-25","comprendre-consensus-ia","historique-signaux-taux-reussite","matchs-live-sans-signal","nouvelle-version-ia-football"];
const rootPublic=path.join(root,'public');
const read=p=>fs.readFileSync(path.join(rootPublic,p),'utf8');
const visible=h=>h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<!--[\s\S]*?-->/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');
const oldMarket=/(?:over\s*\/?\s*under|over\s+2[,.]5|under\s+2[,.]5|btts|más\s+de\s+2[,.]5|menos\s+de\s+2[,.]5|mais\s+de\s+2[,.]5|menos\s+de\s+2[,.]5|тотал\s+(?:больше|меньше)\s*2[,.]5|大\s*2\.5|小\s*2\.5|大小\s*2\.5|2[,.]5\s*goals|2\.5球)/i;
const targetWords={"fr":/une seule équipe ciblée/,"en":/one target team/,"es":/un único equipo objetivo/,"pt-br":/uma única equipe-alvo/,"ru":/целев[а-яё]*\s+команд[а-яё]*/i,"zh-cn":/一支目标球队/};
function walk(o,fn){if(Array.isArray(o))o.forEach(x=>walk(x,fn));else if(o&&typeof o==='object'){fn(o);Object.values(o).forEach(x=>walk(x,fn));}}
for(const p of active){const h=read(p),v=visible(h),lang=p.split('/')[0];assert(!oldMarket.test(v),'old market wording visible on active page '+p);assert(targetWords[lang].test(v),'single target-team explanation missing '+p);const d=(h.match(/<meta name="description" content="([^"]*)"/i)||[])[1]||'',og=(h.match(/<meta property="og:description" content="([^"]*)"/i)||[])[1]||'';assert(/0[,.]5/.test(d)&&/0[,.]5/.test(og),'active description lacks +0.5 scope '+p);const schemas=[...h.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)].map(m=>JSON.parse(m[1]));let web=false;for(const s of schemas)walk(s,o=>{if(o['@type']==='WebPage'&&/0[,.]5/.test(String(o.description||''))&&targetWords[lang].test(String(o.description||'')))web=true;});assert(web,'WebPage JSON-LD metadata does not reflect single-team target '+p);}
const redirects=fs.readFileSync(path.join(rootPublic,'_redirects'),'utf8');
for(const p of oldPages){const h=read(p);assert(/noindex,follow/.test(h),'legacy page must be noindex '+p);assert(/location\.replace/.test(h),'legacy URL fallback redirect missing '+p);assert(!oldMarket.test(visible(h)),'old market copy remains on legacy route '+p);const route=p.replace(/\/index\.html$/,'');assert(redirects.split('\n').some(l=>l.startsWith('/'+route+'/ ')&&l.endsWith('301!')),'forced legacy route redirect missing '+route);}
for(const slug of oldGuides){const h=read('guides/'+slug+'/index.html');assert(!oldMarket.test(visible(h)),'old guide content remains visible '+slug);assert(/http-equiv="refresh"/i.test(h),'old guide HTML fallback redirect missing '+slug);assert(!/<script\b/i.test(h),'old guide redirect stub must remain script-free '+slug);assert(redirects.split('\n').some(l=>l.startsWith('/guides/'+slug+'/ ')&&l.endsWith('301!')),'old guide force redirect missing '+slug);}
const guide=read('guides/equipe-ciblee-plus-0-5/index.html');assert(/une seule équipe ciblée/.test(visible(guide)),'team-specific explainer missing');assert(/autre équipe n’est pas sélectionnée/.test(visible(guide)),'guide does not rule out the other team');
const app=fs.readFileSync(path.join(rootPublic,'app.html'),'utf8');assert(!/TLM_DISPLAY_OU25_ONLY_V1/.test(app),'legacy whole-card market filter remains in app');assert(/Équipe ciblée :/.test(app),'app result card lacks explicit target-team label');assert(/marque au moins un but/.test(app),'app result card lacks team-goal condition');assert(/function appGoal05State\(m\)[\s\S]*?goal05_v2/.test(app)&&/function appMiniVotes\(m\)[\s\S]*?appGoal05State\(m\)/.test(app),'app listing must use goal05 metadata');assert(!/function appMiniVotes\(m\)[\s\S]*?direction==='over'[\s\S]*?function appLogo/.test(app),'app still exposes O/U vote marks');
const home=fs.readFileSync(path.join(rootPublic,'index.html'),'utf8');assert(!/TLM_DISPLAY_OU25_ONLY_V1/.test(home),'legacy whole-card filter remains on home page');assert(/une seule équipe ciblée/.test(visible(home)),'home page does not state one selected team');
const live=fs.readFileSync(path.join(rootPublic,'live-ia.html'),'utf8');assert(/var marketsHtml = ""/.test(live)&&/var scoresHtml = ""/.test(live),'live page still renders secondary market breakdowns');assert(/function liveGoal05State\(m\)/.test(live)&&/function renderLiveGoal05Details\(m\)/.test(live),'live page must use Goal05 state and rendering');assert(!/(?:liveOu25|renderLiveOu25|m\.ou25|TLM_LIVE_OU25)/.test(live),'legacy O/U live implementation remains active');assert(/Équipe ciblée/.test(live),'live page does not label target team');assert(/var targetTeam=/.test(live)&&/if\(isGoal05ForTeam\)/.test(live),'live page accepts recommendations without named +0.5 target');
const seo=fs.readFileSync(path.join(rootPublic,'seo/seo.js'),'utf8');assert(/target_team/.test(seo)&&/marque au moins un but/.test(seo),'SEO results table needs team-specific selection');
console.log('PUBLIC_SEO_SINGLE_TEAM_GOAL05_OK '+active.length+' active pages; '+oldPages.length+' legacy routes; '+oldGuides.length+' redirected guides');
