'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
const home=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const api=fs.readFileSync(path.join(root,'scripts/api_server.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'public/sw.js'),'utf8');
const header=fs.readFileSync(path.join(root,'public/js/global-header.js'),'utf8');
const headerCss=fs.readFileSync(path.join(root,'public/css/global-header.css'),'utf8');
const app=fs.readFileSync(path.join(root,'public/app.html'),'utf8');
const performances=fs.readFileSync(path.join(root,'public/performances.html'),'utf8');
for(const file of ['index.html','live-ia.html','performances.html','bankroll.html','dashboard.html']){
 const text=fs.readFileSync(path.join(root,'public',file),'utf8');
 assert(text.includes('/css/global-header.css?v=20260912-v2'),file+' shared header CSS');
 assert(text.includes('/js/global-header.js?v=20260912-v2'),file+' shared header JS');
 for(const match of text.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!/src=|ld\+json/i.test(match[1]))new vm.Script(match[2],{filename:file});
}
new vm.Script(header,{filename:'global-header.js'});
assert(header.includes("body:not(.tlm-page-app)>nav"),'the shared header must preserve the app bottom navigation');
assert(header.includes("['/','Accueil']")&&header.includes("['/live-ia','Live IA']")&&header.includes("['/performances','Résultats']")&&header.includes("['/bankroll','Bankroll']"));
assert(header.includes("d&&d.locked===false?'Premium':'Gratuit'"),'Premium status must come from server-verified access');
assert(headerCss.includes('@media(max-width:980px)')&&headerCss.includes('.tlm-gh-language'));
assert(home.includes("heroOu25(m).voteCount>0"),'real partial ballots remain visible');
assert(home.includes("state.locked?'?':direction==='over'?'O':direction==='under'?'U':'?'"),'free/paid round masking');
assert(home.includes("voted?(voteState.locked?'?':dir==='over'?'O':dir==='under'?'U':'?'):String(i+1)"),'hero five rounds');
assert(home.includes("tlmVoteCirclesHtml(m)"),'analysis list five rounds');
assert(home.includes("filter(tlmCurrentAnalyzedMatch)"),'finished matches must not stay in the live section');
assert(!home.includes('TLM-HOME-FIXTURES-UI-20260830'),'the obsolete eager loader must not overwrite analyzed matches');
assert(app.includes("m.client_product_eligible===true&&appOu25(m).voteCount>0"),'the app must keep genuine partial live trends');
assert(app.includes("appWasSent(a)||!!a.official_signal_snapshot_id"),'official finished signals must remain in app history');
assert(!performances.includes('>🥇 Standard<')&&!performances.includes('>🥈 Premium<'),'legacy commercial tier labels must not be rendered');
assert(home.includes("Calculé à "),'snapshot minute label');
assert(api.includes('snapshot_score: snapshotScore')&&api.includes('snapshot_score: raw.snapshot_score || null'),'frozen snapshot score API');
assert(home.includes("tlmHomeSectionLoaded={live:true,upcoming:false,history:false}"));
assert(home.includes("name==='upcoming'&&!tlmHomeSectionLoaded.upcoming")&&home.includes("name==='history'&&!tlmHomeSectionLoaded.history"));
assert(home.includes("setHomeSection('live')"));
assert(home.includes("cutoff.setDate(cutoff.getDate()-29)"));
assert(sw.includes('tlm-app-v21-stable-interface-20260912'));
assert(sw.includes('/js/global-header.js?v=20260912-v2')&&sw.includes('/css/global-header.css?v=20260912-v2'));
console.log('OK: header partagé, cinq ronds réels, masquage gratuit, snapshots et sections lazy 30 jours');
