'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
let Database;try{Database=require('better-sqlite3');}catch{Database=require('node:sqlite').DatabaseSync;}
assert.ok(fs.existsSync(path.join(__dirname,'premium_access_projection.js')),'managed pass account projection is missing');
const {createAccessProjection}=require('./premium_access_projection');
const {createLedger,verifyPurchase}=require('./premium_month_pass');
const config={priceId:'price_fixture',productId:'prod_fixture',livemode:false};
const price={id:'price_fixture',active:true,type:'one_time',currency:'eur',unit_amount:1490,livemode:false,product:{id:'prod_fixture',active:true}};
const data=new Database(':memory:'),codes=new Database(':memory:'),ledger=createLedger(data);
codes.exec('CREATE TABLE codes(code TEXT PRIMARY KEY,email TEXT,plan TEXT,active INTEGER,expires_at TEXT,credits_max INTEGER,credits_used INTEGER,credits_date TEXT,created_at TEXT,preferred_language TEXT)');
const projection=createAccessProjection({codesDb:codes,ledger});
const at='2026-01-31T12:00:00.000Z';
function pay(id,email){const purchase=verifyPurchase({id,mode:'payment',status:'complete',payment_status:'paid',livemode:false,amount_total:1490,currency:'eur',payment_intent:'pi_'+id,customer_details:{email},metadata:{tlm_offer:'premium_calendar_month_v1'},line_items:{has_more:false,data:[{quantity:1,price}]}},price,config);ledger.applyPurchase(purchase,{at});}
pay('cs_new','new@example.test');
assert.equal(projection.reconcile('new@example.test',{at,language:'ru'}).active,true);
let row=codes.prepare('SELECT * FROM codes WHERE email=?').get('new@example.test');
assert.equal(row.plan,'premium');assert.equal(row.expires_at,'2026-02-28T12:00:00.000Z');assert.equal(row.preferred_language,'ru');
projection.reconcile('new@example.test',{at});assert.equal(codes.prepare('SELECT count(*) n FROM codes').get().n,1);
projection.reconcile('new@example.test',{at:'2026-02-28T12:00:00.000Z'});
assert.equal(codes.prepare('SELECT active FROM codes').get().active,0);
pay('cs_renew','new@example.test');projection.reconcile('new@example.test',{at:'2026-02-28T12:00:01.000Z'});
assert.equal(codes.prepare('SELECT active FROM codes').get().active,1);
assert.equal(codes.prepare('SELECT expires_at FROM codes').get().expires_at,'2026-03-28T12:00:00.000Z');
codes.prepare('INSERT INTO codes(code,email,plan,active,expires_at) VALUES (?,?,?,?,?)').run('legacy-admin','admin@example.test','elite',1,null);
const before=JSON.stringify(codes.prepare("SELECT * FROM codes WHERE code='legacy-admin'").get());
pay('cs_admin','admin@example.test');assert.equal(projection.reconcile('admin@example.test',{at}).preservedLegacy,true);
projection.reconcile('admin@example.test',{at:'2026-04-01T00:00:00.000Z'});
assert.equal(JSON.stringify(codes.prepare("SELECT * FROM codes WHERE code='legacy-admin'").get()),before);
assert.equal(codes.prepare("SELECT count(*) n FROM codes WHERE email='admin@example.test'").get().n,1);
pay('cs_refund','refund@example.test');projection.reconcile('refund@example.test',{at});
ledger.refund('pi_cs_refund',{at,amountRefunded:1490});projection.reconcile('refund@example.test',{at});
assert.equal(codes.prepare("SELECT active FROM codes WHERE email='refund@example.test'").get().active,0);
assert.equal(projection.reconcile('never-paid@example.test',{at}).active,false);
assert.equal(codes.prepare("SELECT count(*) n FROM codes WHERE email='never-paid@example.test'").get().n,0);
codes.exec("UPDATE codes SET plan='elite' WHERE email='new@example.test'");
assert.throws(()=>projection.reconcile('new@example.test',{at}),'externally promoted managed row must not be downgraded');
assert.equal(codes.prepare("SELECT plan FROM codes WHERE email='new@example.test'").get().plan,'elite');
codes.exec("UPDATE codes SET plan='premium',expires_at=NULL WHERE email='new@example.test'");
assert.throws(()=>projection.reconcile('new@example.test',{at:'2026-05-01T00:00:00Z'}),'lifetime override with same plan must not be revoked');
assert.equal(codes.prepare("SELECT active FROM codes WHERE email='new@example.test'").get().active,1);
codes.close();data.close();console.log('PASS managed pass projection: activation, renewal, exact expiry, refunds, legacy/admin preservation, ownership');
