'use strict';
// Real SQLite + Stripe signature verification; only remote Stripe reads are fake.
const assert=require('node:assert/strict');
const Stripe=require('stripe');
let Database;try{Database=require('better-sqlite3');}catch{Database=require('node:sqlite').DatabaseSync;}
const fs=require('node:fs');
assert.ok(fs.existsSync(require('node:path').join(__dirname,'premium_stripe_adapter.js')),'Premium signed-event adapter is missing');
const {createPremiumStripeAdapter}=require('./premium_stripe_adapter');
const {createLedger}=require('./premium_month_pass');
const secret='whsec_local_fixture_not_a_real_secret';
const sdk=new Stripe('sk_test_local_fixture_not_a_real_key');
const config={priceId:'price_fixture',productId:'prod_fixture',livemode:false};
const price={id:'price_fixture',active:true,type:'one_time',recurring:null,currency:'eur',unit_amount:1490,livemode:false,product:{id:'prod_fixture',active:true}};
const session=(id='cs_fixture',email='buyer@example.test')=>({id,mode:'payment',status:'complete',payment_status:'paid',livemode:false,amount_total:1490,currency:'eur',payment_intent:'pi_'+id,customer_details:{email},line_items:{has_more:false,data:[{quantity:1,price}]},metadata:{tlm_offer:'premium_calendar_month_v1',tlm_referral:'REF_OWNER'}});
async function main(){
 const db=new Database(':memory:'),ledger=createLedger(db);
 ledger.registerReferral('REF_OWNER','owner@example.test');
 let current=session(),currentPrice=structuredClone(price),now='2026-01-31T12:00:00.000Z',failRead=false;
 let charge={id:'ch_fixture',payment_intent:current.payment_intent,livemode:false,paid:true,currency:'eur',amount:1490,amount_refunded:1490};
 const stripe={webhooks:sdk.webhooks,checkout:{sessions:{retrieve:async id=>{if(failRead)throw Error('offline');assert.equal(id,current.id);return structuredClone(current);},list:async args=>{assert.equal(args.payment_intent,charge.payment_intent);return {data:[structuredClone(current)],has_more:false};}}},prices:{retrieve:async id=>{assert.equal(id,config.priceId);return structuredClone(currentPrice);}},charges:{retrieve:async id=>{assert.equal(id,charge.id);return structuredClone(charge);}}};
 const adapter=createPremiumStripeAdapter({stripe,ledger,config,signingSecret:secret,clock:()=>now,isHistoricalCustomer:async email=>email==='legacy@example.test'});
 assert.equal(typeof adapter.createCheckout,'function','one-month Checkout creation is missing');
 let created=null;
 stripe.checkout.sessions.create=async (params,options)=>{created={params,options};return {id:'cs_created',url:'https://checkout.stripe.com/c/pay/cs_created',livemode:false};};
 await assert.rejects(()=>adapter.createCheckout({email:'buyer@example.test',requestId:'request-12345678',language:'ru'}),'sales must be disabled until access tests pass');
 const sales=createPremiumStripeAdapter({stripe,ledger,config:{...config,salesEnabled:true,origin:'https://touslesmatchs.com'},signingSecret:secret,clock:()=>now,isHistoricalCustomer:async()=>false});
 const checkoutResult=await sales.createCheckout({email:' Buyer@example.test ',requestId:'request-12345678',language:'ru',referral:'REF_OWNER'});
 assert.equal(checkoutResult.url,'https://checkout.stripe.com/c/pay/cs_created');
 assert.equal(created.params.mode,'payment');assert.equal(created.params.customer_email,'buyer@example.test');
 assert.deepEqual(created.params.line_items,[{price:'price_fixture',quantity:1}]);
 assert.equal(created.params.locale,'ru');assert.equal(created.params.metadata.tlm_offer,'premium_calendar_month_v1');
 assert.equal(created.params.metadata.tlm_referral,'REF_OWNER');assert.equal(created.params.subscription_data,undefined);
 assert.ok(created.options.idempotencyKey);assert.equal(created.params.payment_method_types,undefined);
 assert.ok(created.params.success_url.startsWith('https://touslesmatchs.com/'));
 currentPrice.active=false;await assert.rejects(()=>sales.createCheckout({email:'buyer@example.test',requestId:'request-12345679'}));currentPrice.active=true;
 currentPrice.unit_amount=1990;await assert.rejects(()=>sales.createCheckout({email:'buyer@example.test',requestId:'request-12345679'}));currentPrice.unit_amount=1490;
 await assert.rejects(()=>sales.createCheckout({email:'bad-email',requestId:'request-12345679'}));
 function signed(type='checkout.session.completed',object={id:current.id},overrides={}){const raw=Buffer.from(JSON.stringify({id:'evt_fixture',type,livemode:false,created:Math.floor(Date.now()/1000),data:{object},...overrides}));return [raw,sdk.webhooks.generateTestHeaderString({payload:raw.toString(),secret})];}
 await assert.rejects(()=>adapter.handle(Buffer.from('{}'),'bad'));
 await assert.rejects(()=>adapter.handle({},'bad'));
 assert.equal(ledger.entitlement('buyer@example.test',now).active,false);
 const valid=signed();await assert.rejects(()=>adapter.handle(Buffer.from(valid[0].toString().replace('cs_fixture','cs_forged')),valid[1]));
 current.payment_status='unpaid';assert.equal((await adapter.handle(...signed())).status,'pending');
 assert.equal(ledger.entitlement('buyer@example.test',now).active,false);
 current.payment_status='paid';
 const result=await adapter.handle(...signed('checkout.session.async_payment_succeeded',{id:current.id,customer_email:'attacker@example.test'}));
 assert.equal(result.status,'granted');assert.equal(result.expiresAt,'2026-02-28T12:00:00.000Z');
 assert.equal(ledger.entitlement('attacker@example.test',now).active,false);
 now='2026-02-02T12:00:00.000Z';assert.equal((await adapter.handle(...signed())).duplicate,true);
 assert.equal(ledger.entitlement('buyer@example.test',now).expiresAt,'2026-02-28T12:00:00.000Z');
 assert.equal(ledger.entitlement('owner@example.test',now).grantCount,1);
 current=session('cs_legacy','legacy@example.test');await adapter.handle(...signed());
 assert.equal(ledger.entitlement('owner@example.test',now).grantCount,1,'historical customer is never a new referral');
 current=session('cs_other','other@example.test');current.metadata.tlm_offer='legacy_offer';
 assert.equal((await adapter.handle(...signed())).status,'ignored');
 current=session('cs_wrong','wrong@example.test');current.line_items.data[0].price={...price,id:'price_wrong'};
 await assert.rejects(()=>adapter.handle(...signed()));assert.equal(ledger.entitlement('wrong@example.test',now).active,false);
 current=session('cs_outage');failRead=true;await assert.rejects(()=>adapter.handle(...signed()));failRead=false;
 assert.equal(db.prepare("SELECT count(*) n FROM premium_pass_payments WHERE session_id='cs_outage'").get().n,0);
 await assert.rejects(()=>adapter.handle(...signed('checkout.session.completed',{id:current.id},{livemode:true})));
 current=session();charge.payment_intent=current.payment_intent;
 assert.equal((await adapter.handle(...signed('charge.refunded',{id:charge.id}))).revoked,true);
 assert.equal(ledger.entitlement('buyer@example.test',now).active,false);
 assert.equal(ledger.entitlement('owner@example.test',now).active,false);
 current=session('cs_refund_first','refunded@example.test');charge.payment_intent=current.payment_intent;
 await adapter.handle(...signed('charge.refunded',{id:charge.id}));
 assert.equal((await adapter.handle(...signed())).active,false);
 current=session('cs_partial','partial@example.test');await adapter.handle(...signed());
 charge.payment_intent=current.payment_intent;charge.amount_refunded=400;
 assert.equal((await adapter.handle(...signed('charge.refunded',{id:charge.id}))).needsReview,true);
 assert.equal(ledger.entitlement('partial@example.test',now).active,true);
 current=session('cs_delayed','delayed@example.test');currentPrice.active=false;currentPrice.product.active=false;
 assert.equal((await adapter.handle(...signed())).active,true,'archiving a product must not cancel an already paid checkout');
 assert.equal((await adapter.handle(...signed('invoice.paid',{id:'in_legacy'}))).status,'ignored');
 assert.equal(ledger.entitlement('delayed@example.test','2026-03-02T12:00:00.000Z').active,false);
 db.close();console.log('PASS signed Premium adapter: signature, tampering, unpaid/async, server reads, replay, legacy, refunds, archive, expiry');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
