'use strict';
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const active=["en/ai-football-predictions/index.html","en/football-predictions-today/index.html","en/index.html","es/index.html","es/pronosticos-futbol-hoy/index.html","es/pronosticos-futbol-ia/index.html","fr/index.html","fr/pronostics-foot-aujourdhui/index.html","fr/pronostics-foot-ia/index.html","pt-br/index.html","pt-br/palpites-futebol-hoje/index.html","pt-br/palpites-futebol-ia/index.html","ru/index.html","ru/prognozy-futbol-ii/index.html","ru/prognozy-futbol-segodnya/index.html","zh-cn/ai-zuqiu-yuce/index.html","zh-cn/index.html","zh-cn/jinri-zuqiu-yuce/index.html"];
const archived=["en/over-2-5-goals-predictions/index.html","en/under-2-5-goals-predictions/index.html","es/pronosticos-mas-de-2-5-goles/index.html","es/pronosticos-menos-de-2-5-goles/index.html","fr/pronostics-over-2-5/index.html","fr/pronostics-under-2-5/index.html","pt-br/palpites-mais-de-2-5-gols/index.html","pt-br/palpites-menos-de-2-5-gols/index.html","ru/total-bolshe-2-5/index.html","ru/total-menshe-2-5/index.html","zh-cn/da-2-5-qiu-yuce/index.html","zh-cn/xiao-2-5-qiu-yuce/index.html"];
const expectedFaq={"fr":"Quelle est la stratégie active ?","en":"What is the active strategy?","es":"¿Cuál es la estrategia activa?","pt-br":"Qual é a estratégia ativa?","ru":"Какая стратегия действует сейчас?","zh-cn":"当前策略是什么？"};
function read(p){return fs.readFileSync(path.join(root,'public',p),'utf8');}
function meta(html,pattern){const m=html.match(pattern);assert(m,'missing metadata '+pattern);return m[1];}
function jsonLd(html){return [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)].map(m=>JSON.parse(m[1]));}
function walk(o,fn){if(Array.isArray(o))o.forEach(x=>walk(x,fn));else if(o&&typeof o==='object'){fn(o);Object.values(o).forEach(x=>walk(x,fn));}}
const legacy=/(?:over\s*\/?\s*under\s*2[,.]5|over\s+2[,.]5\s+goals|under\s+2[,.]5\s+goals|over\/under|más\s+de\s+2[,.]5|menos\s+de\s+2[,.]5|mais\s+de\s+2[,.]5|menos\s+de\s+2[,.]5|тотал\s+(?:больше|меньше)\s*2[,.]5|大\s*2\.5|小\s*2\.5|大小\s*2\.5)/i;
const oldRoute=/(?:over[-\/]?2[-.,]5|under[-\/]?2[-.,]5|pronosticos-(?:mas|menos)-de-2-5|palpites-(?:mais|menos)-de-2-5|total-(?:bolshe|menshe)|(?:da|xiao)-2-5|pronostics-(?:over|under)-2-5)/i;
for(const p of active){const h=read(p);const visible=h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ');assert(!legacy.test(visible),'legacy O/U copy visible on '+p);assert(!oldRoute.test(h.match(/<main[\s\S]*?<\/main>/i)?.[0]||h),'active page links to archived O/U page: '+p);const d=meta(h,/<meta name="description" content="([^"]*)"/i);const og=meta(h,/<meta property="og:description" content="([^"]*)"/i);assert(/[+]0[,.]5/.test(d)&&/[+]0[,.]5/.test(og),'active strategy missing in descriptions: '+p);const q=expectedFaq[p.split('/')[0]];assert(visible.includes(q),'active +0.5 FAQ missing: '+p);const schemas=jsonLd(h);let faq=false,web=false;for(const s of schemas)walk(s,o=>{if(o['@type']==='FAQPage'&&(o.mainEntity||[]).some(x=>x.name===q&&!legacy.test(JSON.stringify(x))))faq=true;if(o['@type']==='WebPage'&&/[+]0[,.]5/.test(String(o.description||'')))web=true;});assert(faq,'FAQ JSON-LD missing current strategy: '+p);assert(web,'WebPage JSON-LD missing +0.5: '+p);}
for(const p of archived){const h=read(p);const t=meta(h,/<title>([\s\S]*?)<\/title>/i);const d=meta(h,/<meta name="description" content="([^"]*)"/i);const og=meta(h,/<meta property="og:title" content="([^"]*)"/i);assert(/archive|archivo|arquivo|архив|档案/i.test(t)&&/archive|archivo|arquivo|архив|档案/i.test(og),'archive title missing: '+p);assert(/archive|archivo|arquivo|архив|档案/i.test(d),'archive meta description missing: '+p);assert(!/(?:today|aujourd.?hui|hoy|hoje|сегодня|今日)/i.test(t),'archive still titled as current predictions: '+p);let web=false;for(const s of jsonLd(h))walk(s,o=>{if(o['@type']==='WebPage'&&/archive|archivo|arquivo|архив|档案/i.test(String(o.description||'')))web=true;});assert(web,'archive WebPage schema not archival: '+p);}
console.log('PUBLIC_SEO_GOAL05_OK '+active.length+' active pages; '+archived.length+' historical pages');
