'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'api_server.js'),'utf8');
const start=source.indexOf('function shouldRetryDeepSeekOu25RateLimit(');
const end=source.indexOf('\n// Un timeout ou une erreur HTTP',start);
assert(start>=0&&end>start,'transient policy absent');
const context={};vm.createContext(context);vm.runInContext(source.slice(start,end),context);
const same={url:'https://openrouter.ai/api/v1/chat/completions',model:'deepseek/deepseek-chat'};
const input={agentName:'DeepSeek-V3',provider:same,response:{_httpStatus:429,error:{message:'Rate limit exceeded'}},attempt:1,minute:39,elapsedMs:950};
assert.equal(context.shouldRetryDeepSeekOu25RateLimit(input),true);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,response:{_httpStatus:429,error:{message:'Global OpenRouter Paris daily budget reached'}}}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,response:{_httpStatus:402}}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,provider:{...same,model:'openai/gpt-5.6-luna'}}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,agentName:'Perplexity-Web'}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,minute:46}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,attempt:2}),false);
assert.equal(context.shouldRetryDeepSeekOu25RateLimit({...input,elapsedMs:20000}),false);
assert(source.includes('promptVersion: `fallback_${agCfg.name}_429_retry`'),'retry gate needs distinct idempotency key');
assert(source.includes('retryGuard.canProceed(db'),'retry must respect quotas and budgets');
assert(source.includes('attemptTimeoutMs = AGENT_TIMEOUT_MS - (Date.now() - agentAttemptWindowStartedAt)'),'retry cannot extend seat timeout');
console.log('PASS DeepSeek: one same-model HTTP 429 retry only inside window and existing quotas; global budget 429 never retried');
